In [331]:
import pandas as pd
import os

In [332]:
BASE_DIR = os.path.dirname(os.getcwd())

df = pd.read_csv(os.path.join(BASE_DIR, "data", "raw", "europe_sales.csv"))

df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Europe,Cz@ech Republic,Bevera2ges,Off2line,C,09-12-2011,01-01-2010,478051030,9/29/2011,4778,47.45,31.79,226716.10,151892.62,74823.48
1,Europe,Bosnia and Herzegovina,Clothes,Online,M,10/14/2013,02-01-2010,919133651,11-04-2013,927,109.28,35.84,101302.56,33223.68,68078.88
2,Europe,Austria,Cereal,Offline,C,8/13/2014,03-01-2010,987410676,09-06-2014,5616,205.70,117.11,1155211.20,657689.76,497521.44
3,Europe,Bulgaria,Office Supplies,Online,L,10/31/2010,04-01-2010,672330081,11/29/2010,6266,651.21,524.96,4080481.86,3289399.36,791082.50
4,Europe,Estonia,Fruits,Online,L,9/28/2016,05-01-2010,579463422,11-01-2016,4958,9.33,6.92,46258.14,34309.36,11948.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1325,Europe,Norway,Personal Care,Offline,M,1/14/2014,18-08-2013,634033286,1/15/2014,3394,81.73,56.67,277391.62,192337.98,85053.64
1326,Europe,Ukraine,Cereal,Offline,L,4/14/2014,19-08-2013,559183347,5/21/2014,3633,205.70,117.11,747308.10,425460.63,321847.47
1327,Europe,Armenia,Meat,Offline,M,11-09-2015,20-08-2013,781416594,12/23/2015,7390,421.89,364.69,3117767.10,2695059.10,422708.00
1328,Europe,Denmark,Clothes,Offline,H,05-09-2012,21-08-2013,713357150,06-03-2012,7088,109.28,35.84,774576.64,254033.92,520542.72
1329,Europe,Finland,Clothes,Online,L,4/22/2014,22-08-2013,906794202,05-11-2014,9410,109.28,35.84,1028324.80,337254.40,691070.40

In [333]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1330 entries, 0 to 1329
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          1330 non-null   str
 1   Country         1330 non-null   str
 2   Item Type       1330 non-null   str
 3   Sales Channel   1330 non-null   str
 4   Order Priority  1330 non-null   str
 5   Order Date      1330 non-null   str
 6   Date            1330 non-null   str
 7   Order ID        1330 non-null   int64
 8   Ship Date       1330 non-null   str
 9   Units Sold      1330 non-null   int64
 10  Unit Price      1330 non-null   float64
 11  Unit Cost       1330 non-null   float64
 12  Total Revenue   1330 non-null   float64
 13  Total Cost      1330 non-null   float64
 14  Total Profit    1330 non-null   float64
dtypes: float64(5), int64(2), str(8)
memory usage: 156.0 KB

In [334]:
df.describe()
df.isnull().sum()
df.shape

(1330, 15)

In [335]:
date_cols = ['Order Date', 'Date', 'Ship Date']

for col in date_cols:
    df[col] = pd.to_datetime(df[col], format='mixed')

In [336]:
string_cols = df.select_dtypes(include='object').columns

for col in string_cols:
    df[col] = (
        df[col]
        .str.replace(r'[^a-zA-Z\s]', '', regex=True)  # remove symbols + numbers
        .str.replace(r'\s+', ' ', regex=True)         # fix spaces
        .str.strip()
    )

C:\Users\Soy\AppData\Local\Temp\ipykernel_6488\12928346.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_cols = df.select_dtypes(include='object').columns

In [337]:
string_cols

Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority'], dtype='str')

In [338]:
df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Europe,Czech Republic,Beverages,Offline,C,2011-09-12,2010-01-01,478051030,2011-09-29,4778,47.45,31.79,226716.10,151892.62,74823.48
1,Europe,Bosnia and Herzegovina,Clothes,Online,M,2013-10-14,2010-02-01,919133651,2013-11-04,927,109.28,35.84,101302.56,33223.68,68078.88
2,Europe,Austria,Cereal,Offline,C,2014-08-13,2010-03-01,987410676,2014-09-06,5616,205.70,117.11,1155211.20,657689.76,497521.44
3,Europe,Bulgaria,Office Supplies,Online,L,2010-10-31,2010-04-01,672330081,2010-11-29,6266,651.21,524.96,4080481.86,3289399.36,791082.50
4,Europe,Estonia,Fruits,Online,L,2016-09-28,2010-05-01,579463422,2016-11-01,4958,9.33,6.92,46258.14,34309.36,11948.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1325,Europe,Norway,Personal Care,Offline,M,2014-01-14,2013-08-18,634033286,2014-01-15,3394,81.73,56.67,277391.62,192337.98,85053.64
1326,Europe,Ukraine,Cereal,Offline,L,2014-04-14,2013-08-19,559183347,2014-05-21,3633,205.70,117.11,747308.10,425460.63,321847.47
1327,Europe,Armenia,Meat,Offline,M,2015-11-09,2013-08-20,781416594,2015-12-23,7390,421.89,364.69,3117767.10,2695059.10,422708.00
1328,Europe,Denmark,Clothes,Offline,H,2012-05-09,2013-08-21,713357150,2012-06-03,7088,109.28,35.84,774576.64,254033.92,520542.72
1329,Europe,Finland,Clothes,Online,L,2014-04-22,2013-08-22,906794202,2014-05-11,9410,109.28,35.84,1028324.80,337254.40,691070.40

In [339]:
file_path = os.path.join(BASE_DIR, "data", "processed", "cleaned_europe_sales.csv")

df.to_csv(file_path,index=False)